# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
print(np.show_config())
np.version.version

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
None


'1.20.3'

#### 3. Create a null vector of size 10

In [4]:
null_arr=np.zeros(10,dtype="int")
null_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array

In [5]:
a = null_arr.size
b = null_arr.itemsize
print("{} bytes".format(a*b))

40 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
np.array?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [12]:
npm=np.arange(10,50,5)
npm

array([10, 15, 20, 25, 30, 35, 40, 45])

#### 8.  Reverse a vector (first element becomes last)

In [13]:
np.flipud(npm)

array([45, 40, 35, 30, 25, 20, 15, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.random.randint(0,9,(3,3))

array([[2, 2, 4],
       [8, 7, 6],
       [2, 3, 2]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [19]:
arr = np.array([1,2,0,0,4,0])
ans = np.where(arr!=0)
#ans =  np.nonzero(arr)
ans
# np.where?

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [27]:
np.random.random((3,3,3))

array([[[0.52497899, 0.25163394, 0.23620637],
        [0.9842549 , 0.04977335, 0.95631392],
        [0.02610331, 0.13148922, 0.58522821]],

       [[0.05776969, 0.18594681, 0.87264753],
        [0.45890425, 0.31881612, 0.61777252],
        [0.0083008 , 0.09355962, 0.75561441]],

       [[0.30067144, 0.3538955 , 0.43799075],
        [0.47837645, 0.18818706, 0.76553279],
        [0.02253643, 0.69544195, 0.0318427 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
arr=np.random.random((10,10))
print(arr)
print("arr of max",np.max(arr))
print("arr of min",np.min(arr))

[[0.64141674 0.76992191 0.39018297 0.5330812  0.31224573 0.75191333
  0.07159691 0.01115235 0.86716594 0.6939839 ]
 [0.18352671 0.23391504 0.4391321  0.35918889 0.95020502 0.80247689
  0.27720693 0.05105028 0.60438958 0.34335777]
 [0.7290399  0.84420286 0.33330434 0.19626716 0.10803174 0.50534147
  0.78209834 0.32808327 0.59576281 0.52103645]
 [0.47944532 0.34037783 0.81142197 0.85313374 0.21295672 0.56330302
  0.45139566 0.43212774 0.91204848 0.98362487]
 [0.08858629 0.12743836 0.09100496 0.6726954  0.55991161 0.62712697
  0.05514133 0.03891961 0.35349112 0.09702335]
 [0.69597153 0.83742083 0.43210008 0.51931764 0.51880814 0.56108589
  0.26794241 0.02282404 0.7519613  0.10437559]
 [0.1895053  0.32708524 0.14770449 0.17871938 0.22316781 0.55039278
  0.62165447 0.64904202 0.94330838 0.01609435]
 [0.16019003 0.95241206 0.65004743 0.52159078 0.33453329 0.92837277
  0.09980302 0.75894297 0.75774096 0.44615339]
 [0.60713584 0.33422912 0.30454345 0.99048323 0.68359157 0.22943482
  0.67590745

#### 14. Create a random vector of size 30 and find the mean value

In [29]:
arr1= np.random.random(30)
print(arr1)
means_arr=np.mean(arr)
means_arr

[0.26813227 0.0593989  0.1947372  0.92431828 0.34614395 0.34251814
 0.27275416 0.4840163  0.38324376 0.64595934 0.11915761 0.60348636
 0.41097902 0.25323159 0.79670723 0.14479489 0.91925589 0.04192598
 0.99848281 0.11649905 0.67729248 0.26744644 0.46594001 0.56118491
 0.75218134 0.35570455 0.48174161 0.65925162 0.52086679 0.09685123]


0.4658486971142729

#### 15. Create a 2d array with 1 on the border and 0 inside

In [30]:
arr1 =np.ones((5,5),dtype="int64")
arr1[1:4,1:4]=0
arr1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

#### 16. How to add a border (filled with 0's) around an existing array?

In [38]:
ans = np.ones((5,5))
np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [39]:
np.nan?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))#The very short and crispy answer is false
#because some floating-point numbers cannot be represented exactly.

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [41]:
ans = np.diag([1,2,3,4],-1)
ans

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [42]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [43]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)